"""HTML report renderer — Jinja2 with inline fallback template."""

import os
from jinja2 import Environment, FileSystemLoader, select_autoescape, Template
from outreach_schemas import PackReport


DEFAULT_TEMPLATE = """
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>{{ report.pack_name }} — Audit</title>
  <style>
    body { font-family: Inter, Arial, sans-serif; color:#111; margin:24px; }
    header { border-bottom:1px solid #eee; margin-bottom:16px; padding-bottom:8px; }
    h1 { margin:0; font-size:20px; }
    .meta { color:#666; font-size:13px; margin-top:6px; }
    .section { margin-top:18px; }
    table { width:100%; border-collapse:collapse; margin-top:8px; }
    th, td { text-align:left; padding:8px; border-bottom:1px solid #f2f2f2; }
    .badge { display:inline-block; padding:4px 8px; background:#111; color:#fff; border-radius:4px; font-size:12px; }
    .pass { color:#0a7d2c; }
    .fail { color:#a40000; }
  </style>
</head>
<body>
  <header>
    <h1>{{ report.pack_name }} <span class="badge">{{ report.forest_verdict.top_style_match }}</span></h1>
    <div class="meta">Analyzed: {{ report.analyzed_at }} • Alignment pass rate: {{ (report.alignment_pass_rate * 100) | round(1) }}%</div>
    <div class="meta">Avg alignment: {{ (report.avg_alignment * 100) | round(1) }}% • Best segment: {{ (report.best_segment_score * 100) | round(1) }}%</div>
  </header>

  <div class="section">
    <h2>Key findings</h2>
    <ul>
      {% for k in report.key_findings %}
      <li>{{ k }}</li>
      {% endfor %}
    </ul>
  </div>

  <div class="section">
    <h2>Category distribution</h2>
    <table>
      <thead><tr><th>Category</th><th>Count</th></tr></thead>
      <tbody>
      {% for k,v in report.category_distribution.items() %}
        <tr><td>{{ k }}</td><td>{{ v }}</td></tr>
      {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="section">
    <h2>Top segments</h2>
    <table>
      <thead><tr><th>Segment</th><th>Matched baseline</th><th>Score</th><th>Pass</th></tr></thead>
      <tbody>
      {% for s in report.segment_breakdown[:10] %}
        <tr>
          <td>{{ s.segment_name }}</td>
          <td>{{ s.matched_baseline }}</td>
          <td>{{ (s.alignment_score * 100) | round(1) }}%</td>
          <td class="{{ 'pass' if s.pass_threshold else 'fail' }}">{{ "yes" if s.pass_threshold else "no" }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>

  <footer style="margin-top:28px; color:#777; font-size:12px;">
    Report generated by Legion Intelligence — deterministic fire test. For full audit, reply to the email.
  </footer>
</body>
</html>
"""


def render_report_html(report: PackReport, template_dir: str = "templates") -> bytes:
    template_file = os.path.join(template_dir, "report_template.html")
    if os.path.isdir(template_dir) and os.path.exists(template_file):
        env = Environment(
            loader=FileSystemLoader(template_dir),
            autoescape=select_autoescape(["html", "xml"]),
        )
        template = env.get_template("report_template.html")
        html_out = template.render(report=report.dict())
    else:
        env = Environment(autoescape=select_autoescape(["html", "xml"]))
        template = Template(DEFAULT_TEMPLATE)
        html_out = template.render(report=report.dict())
    return html_out.encode("utf-8")