# -*- coding: utf-8 -*-
"""
🪐 SOVEREIGN WORKSPACE CONFIGURATION & ENV GENERATOR
Provides automated bare-metal workstation auditing, local path detection,
and secure .env file generation for the Sovereign AI Audio Suite.
"""

import os
import sys
import socket
import json
from pathlib import Path

# Common local search paths for database volumes across Windows drives
DRIVES = ["C:", "D:", "E:", "F:"]
DUCKDB_SUBPATHS = [
    Path("STUDIES_BACKUP/data/metadata/sonic_core_v2.duckdb"),
    Path("WEB CASE STUDY/data/metadata/sonic_core_v2.duckdb"),
    Path("data/metadata/sonic_core_v2.duckdb")
]
LANCEDB_SUBPATHS = [
    Path("STUDIES_BACKUP/vectors/lancedb_store"),
    Path("WEB CASE STUDY/vectors/lancedb_store"),
    Path("vectors/lancedb_store")
]

def check_port(port: int) -> bool:
    """Check if a local loopback port is active and listening."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.settimeout(0.1)
        return s.connect_ex(("127.0.0.1", port)) == 0

def find_local_path(subpaths, is_file=True) -> str:
    """Scan mounted physical drives to locate target directories or files."""
    for drive in DRIVES:
        for subpath in subpaths:
            full_path = Path(f"{drive}/") / subpath
            if is_file and full_path.is_file():
                return str(full_path).replace("\\", "/")
            elif not is_file and full_path.is_dir():
                return str(full_path).replace("\\", "/")
    return ""

def main():
    print("=" * 80)
    print("🪐 SOVEREIGN WORKSPACE .ENV GENERATOR & AUDITOR")
    print("=" * 80)

    # 1. Audit System Ports
    print("\n🛰️  Checking Active Services (Ports):")
    ports_to_check = {
        6379: "Ray GCS / Redis Service",
        8265: "Ray Web Dashboard",
        1234: "LM Studio Daemon (llmster)",
        8001: "Sovereign FastAPI Gateway",
        8003: "LanceDB MCP RAG Server"
    }
    active_services = {}
    for port, label in ports_to_check.items():
        is_active = check_port(port)
        active_services[port] = is_active
        status = "🟢 ACTIVE" if is_active else "⚪ INACTIVE"
        print(f"  - Port {port:<5} : {status:<10} ({label})")

    # 2. Search for Database Files on Bare-Metal Drives
    print("\n📁 Scanning Local Storage Drives for Databases:")
    
    # Locate DuckDB
    duckdb_path = find_local_path(DUCKDB_SUBPATHS, is_file=True)
    if duckdb_path:
        print(f"  - DuckDB:  🟢 FOUND at '{duckdb_path}'")
    else:
        duckdb_path = "C:/STUDIES_BACKUP/data/metadata/sonic_core_v2.duckdb"
        print(f"  - DuckDB:  ⚠️  NOT FOUND (Defaulting config path to '{duckdb_path}')")

    # Locate LanceDB
    lancedb_path = find_local_path(LANCEDB_SUBPATHS, is_file=False)
    if lancedb_path:
        print(f"  - LanceDB: 🟢 FOUND at '{lancedb_path}'")
    else:
        lancedb_path = "C:/STUDIES_BACKUP/vectors/lancedb_store"
        print(f"  - LanceDB: ⚠️  NOT FOUND (Defaulting config path to '{lancedb_path}')")

    # 3. Formulate the .env Contents
    print("\n📝 Formulating Safe Environment Configuration...")
    
    # Read existing key if present to prevent overwriting validated tokens
    existing_key = "AIzaSyYour_Actual_Validated_AI_Studio_Key_Here"
    env_file = Path(".env")
    if env_file.is_file():
        try:
            with open(env_file, "r") as f:
                for line in f:
                    if "GEMINI_API_KEY=" in line:
                        potential_key = line.split("=", 1)[1].strip()
                        if potential_key and not potential_key.startswith("AIzaSyYour_Actual"):
                            existing_key = potential_key
                            print("  - Found existing GEMINI_API_KEY in .env. Preserving token.")
        except Exception:
            pass

    env_content = f"""# ==============================================================================
# 🪐 SOVEREIGN WORKSPACE ENVIRONMENT CONFIGURATION
# Auto-generated by sovereign_env_generator.py
# ==============================================================================

# Google AI Studio API Access Key
# Replace this placeholder with your actual key to activate Cloud-Hybrid reasoning
GEMINI_API_KEY={existing_key}

# Ray Cluster Configuration
RAY_ADDRESS=auto
RAY_NAMESPACE=legion

# Physical Storage Paths (Normalized for multi-process environments)
LOCAL_DUCKDB_PATH={duckdb_path}
LANCEDB_PATH={lancedb_path}

# Local Microservice Gateway Configuration
SOVEREIGN_GATEWAY_PORT=8001
LANCE_RAG_SERVER_PORT=8003
LM_STUDIO_API_PORT=1234
"""

    # 4. Write Configuration
    try:
        with open(env_file, "w") as f:
            f.write(env_content)
        print(f"\n🟢 SUCCESS: Configuration file written cleanly to: {env_file.resolve()}")
    except Exception as e:
        print(f"\n❌ ERROR: Failed to write .env file: {e}")
        sys.exit(1)

    print("\n" + "=" * 80)
    print("🟢 ENVIRONMENT GENERATOR COMPLETE")
    print("=" * 80)
    print("🚀 Next Steps:")
    print("  1. Open '.env' in your workstation root directory.")
    print("  2. Replace the GEMINI_API_KEY value with your real Gemini API key.")
    print("  3. Run 'system_environment_validator.py' to verify alignment.")
    print("=" * 80)

if __name__ == "__main__":
    main()
