/* DO NOT EDIT THIS FILE - it is machine generated by setup_cpp_pipeline.py */
#include <jni.h>

#ifndef _Included_ai_pipeline_NativeDuckDBBridge
#define _Included_ai_pipeline_NativeDuckDBBridge
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     ai_pipeline_NativeDuckDBBridge
 * Method:    executeVectorPushdownSearch
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_pipeline_NativeDuckDBBridge_executeVectorPushdownSearch
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
