# generate_mastering_playbooks.py
import os
import json
from typing import List, Dict, Any

# --- Configuration ---
# This path is based on your ray_py_analyzer output and the described summary
MASTERING_SWARM_SUMMARY_PATH = r"c:\WEB CASE STUDY\AI_Logs\mastering_swarm_summary.json"
OUTPUT_PLAYBOOKS_PATH = r"c:\WEB CASE STUDY\mastering_playbooks.json"

# Mock structure for mastering_swarm_summary.json
# In a real scenario, this would be generated by parsing your Python DSP files
MOCK_MASTERING_SWARM_SUMMARY = {
    "analysis_timestamp": "2024-06-20T10:00:00Z",
    "total_scripts_analyzed": 240,
    "mastering_scripts_found": [
        {
            "script_name": "smart_mastering_pipeline.py",
            "filepath": "c:\\WEB CASE STUDY\\sonic_dna_engine\\smart_mastering_pipeline.py",
            "impact_score": 0.95, # Higher impact score for more critical/complex scripts
            "pedalboard_effects_chain": [
                {"name": "HighpassFilter", "params": {"cutoff_frequency_hz": 30.0}},
                {"name": "Compressor", "params": {"threshold_db": "AI_SYNTH", "ratio": "AI_SYNTH", "attack_ms": "AI_SYNTH", "release_ms": "AI_SYNTH"}},
                {"name": "Gain", "params": {"gain_db": "AI_SYNTH"}},
                {"name": "Clipping", "params": {"threshold_db": -1.0}},
                {"name": "Limiter", "params": {"threshold_db": "AI_SYNTH", "release_ms": "AI_SYNTH"}}
            ],
            "input_parameters": ["input_filename (str)"],
            "output_parameters": ["output_filepath (str)"],
            "target_audio_features": ["rms_db", "crest_factor", "spectral_centroid"],
            "mastering_goal": "AI-driven dynamic mastering, style-matched loudness and dynamics.",
            "description": "Applies a dynamically generated mastering chain based on predicted track style.",
            "llm_summary": "This pipeline embodies the 'Smart Mastering' concept, using an RF Classifier to determine musical style, and a PyTorch network to synthesize specific Pedalboard parameters. It processes audio segment-by-segment for adaptive, intelligent loudness and dynamic range control."
        },
        {
            "script_name": "dynamic_segment_master.py",
            "filepath": "c:\\WEB CASE STUDY\\sonic_dna_engine\\dynamic_segment_master.py",
            "impact_score": 0.80,
            "pedalboard_effects_chain": [
                {"name": "HighpassFilter", "params": {"cutoff_frequency_hz": 30.0}},
                {"name": "Compressor", "params": {"threshold_db": -20.0, "ratio": 3.0, "attack_ms": 10.0, "release_ms": 100.0}},
                {"name": "Gain", "params": {"gain_db": "DYNAMIC_ADJUSTMENT"}},
                {"name": "Clipping", "params": {"threshold_db": -1.0}},
                {"name": "Limiter", "params": {"threshold_db": -0.3}}
            ],
            "input_parameters": ["input_filename (str)", "custom_output_filepath (Optional[str])"],
            "output_parameters": ["mastered_filepath (str)"],
            "target_audio_features": ["rms_db (target)", "crest_factor (target)"],
            "mastering_goal": "Align track segments to a pre-defined LanceDB baseline for consistent loudness and dynamics.",
            "description": "Segment-based mastering with static Compressor/Limiter and dynamic Gain to match baseline metrics.",
            "llm_summary": "A foundational dynamic mastering tool that uses LanceDB baselines to drive RMS and crest factor matching. It's ideal for bringing a track's segments into alignment with a known reference, like a Chris Lake track. Includes sub-bass phase correction."
        },
        {
            "script_name": "split_and_master_pipeline.py",
            "filepath": "c:\\WEB CASE STUDY\\sonic_dna_engine\\split_and_master_pipeline.py",
            "impact_score": 0.70,
            "pedalboard_effects_chain": "N/A (focuses on separation and analysis, not direct mastering chain)",
            "input_parameters": ["target_filename (str)"],
            "output_parameters": ["report_filepath (str)"],
            "target_audio_features": ["rms_db", "crest_factor", "spectral_centroid", "sub_bass_energy", "bass_energy", "mid_energy", "high_energy"],
            "mastering_goal": "Stem separation, analysis against Chris Lake baselines, and mix recommendations.",
            "description": "Separates a track into stems, analyzes each, and provides mix adjustment recommendations.",
            "llm_summary": "This pipeline acts as an 'AI Mix Engineer', separating a full mix into individual stems (drums, bass, vocals, other) using Demucs. It then critically analyzes each stem against a Chris Lake stem reference, identifying sonic deviations and generating actionable advice for gain or compression adjustments. A crucial tool for pre-mastering mix audits."
        },
        {
            "script_name": "master_stem_alignment.py", # Hypothetical script from previous turns
            "filepath": "c:\\WEB CASE STUDY\\sonic_dna_engine\\master_stem_alignment.py",
            "impact_score": 0.85,
            "pedalboard_effects_chain": [
                {"name": "HighpassFilter", "params": {"cutoff_frequency_hz": 25.0}},
                {"name": "PeakFilter", "params": {"cutoff_frequency_hz": 250, "gain_db": -1.0, "q": 1.0}},
                {"name": "Compressor", "params": {"threshold_db": -14, "ratio": 2.5, "attack_ms": 10, "release_ms": 100}},
                {"name": "Gain", "params": {"gain_db": 3.0}},
                {"name": "Limiter", "params": {"threshold_db": -0.1, "release_ms": 90}}
            ],
            "input_parameters": ["drum_stem_path (str)", "hat_stem_path (str)", "other_stem_path (str)"],
            "output_parameters": ["output_master_path (str)"],
            "target_audio_features": ["rms_db (overall)", "crest_factor (overall)", "high_energy (hats)"],
            "mastering_goal": "Re-assemble individual stems into a master, applying targeted fixes (e.g., mono sub-bass, boosted hats) and overall glue.",
            "description": "Takes individual stems, applies specific processing (e.g., mono drums, boosted hats), and sums them to a final master with a glue compressor and limiter.",
            "llm_summary": "This script is designed for 'stem mastering', where individual components of a mix (drums, hats, other) are treated independently before being summed and mastered. It includes targeted fixes for common mix issues like wide sub-bass and buried high-hats, ensuring a cohesive and impactful final master."
        }
    ]
}


def generate_mastering_playbooks(summary_path: str, output_path: str, top_n: int = 10) -> str:
    """
    Reads the mastering swarm summary, identifies top mastering scripts,
    and generates structured playbooks for each.
    """
    if not os.path.exists(os.path.dirname(output_path)):
        os.makedirs(os.path.dirname(output_path))

    # In a real scenario, we would load from summary_path
    # For this demo, we use the mock data
    # try:
    #     with open(summary_path, 'r', encoding='utf-8') as f:
    #         swarm_summary = json.load(f)
    # except FileNotFoundError:
    #     print(f"Error: {summary_path} not found. Using mock data.", file=sys.stderr)
    swarm_summary = MOCK_MASTERING_SWARM_SUMMARY # Use mock data for demo

    mastering_scripts = swarm_summary.get("mastering_scripts_found", [])

    # Sort by impact score to get the top N
    mastering_scripts.sort(key=lambda x: x.get("impact_score", 0), reverse=True)
    top_scripts = mastering_scripts[:top_n]

    playbooks = []
    for script in top_scripts:
        playbook_entry = {
            "name": script.get("script_name"),
            "filepath": script.get("filepath"),
            "impact_score": script.get("impact_score"),
            "description": script.get("description"),
            "llm_summary": script.get("llm_summary"),
            "mastering_goal": script.get("mastering_goal"),
            "input_parameters": script.get("input_parameters"),
            "output_parameters": script.get("output_parameters"),
            "target_audio_features": script.get("target_audio_features"),
            "pedalboard_effects_chain": script.get("pedalboard_effects_chain", "N/A - Check LLM Summary if analysis only.")
        }
        playbooks.append(playbook_entry)

    final_playbook_output = {
        "generated_at": os.path.getmtime(summary_path) if os.path.exists(summary_path) else time.time(), # Use summary's timestamp if it existed
        "total_playbooks_generated": len(playbooks),
        "playbooks": playbooks
    }

    try:
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(final_playbook_output, f, indent=4)
        return f"[SUCCESS] Mastering playbooks generated and saved to: {output_path}"
    except Exception as e:
        return f"[ERROR] Failed to save mastering playbooks: {e}"

if __name__ == "__main__":
    # --- DEMO ---
    # Create a dummy summary file for the demo if it doesn't exist
    if not os.path.exists(os.path.dirname(MASTERING_SWARM_SUMMARY_PATH)):
        os.makedirs(os.path.dirname(MASTERING_SWARM_SUMMARY_PATH))
    with open(MASTERING_SWARM_SUMMARY_PATH, 'w', encoding='utf-8') as f:
        json.dump(MOCK_MASTERING_SWARM_SUMMARY, f, indent=4)
        
    print("--- Running Mastering Playbook Generation Demo ---")
    result = generate_mastering_playbooks(MASTERING_SWARM_SUMMARY_PATH, OUTPUT_PLAYBOOKS_PATH)
    print(result)

    if "SUCCESS" in result:
        print(f"\nCheck the generated file at: {OUTPUT_PLAYBOOKS_PATH}")
        with open(OUTPUT_PLAYBOOKS_PATH, 'r', encoding='utf-8') as f:
            playbooks_content = json.load(f)
            print("\n--- Sample Playbook Output ---")
            print(json.dumps(playbooks_content["playbooks"][0], indent=2))
